---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: script
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: folder
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.24.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.netflix.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    fake-ip-filter:
    - "+.pool.ntp.org"
    - ntp7.*.com
    - ntp6.*.com
    - ntp5.*.com
    - ntp4.*.com
    - ntp3.*.com
    - ntp2.*.com
    - ntp1.*.com
    - ntp.*.com
    - time7.*.com
    - time6.*.com
    - time5.*.com
    - time4.*.com
    - time3.*.com
    - time2.*.com
    - time1.*.com
    - time.*.apple.com
    - time.*.edu.cn
    - time.*.gov
    - time.*.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - time1.cloud.tencent.com
    - "*.ntp.org"
    - "*.time.edu"
    - "*.lan"
    - "*.ntp.org.cn"
    - "*.time.edu.cn"
    - "+.*"
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 180.131.144.144
  - 180.131.145.145
  - https://dns.google/dns-query
  - tls://dns.google
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - "+.google.com"
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
proxy-providers:
  Paket-Akrabb:
    type: http
    path: ./proxy_provider/akunakrab.yaml
    url: https://raw.githubusercontent.com/mwnsofficial/config-online/main/akunakrab.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  Paket-Flexx:
    type: http
    path: ./proxy_provider/akunflex.yaml
    url: https://raw.githubusercontent.com/mwnsofficial/config-online/main/akunflex.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
proxy-groups:
- name: UMUM
  type: select
  disable-udp: false
  proxies:
  - MANUAL
  - AUTO
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: MANUAL
  type: select
  disable-udp: false
  use:
  - Paket-Akrabb
  - Paket-Flexx
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: AUTO
  type: url-test
  disable-udp: false
  use:
  - Paket-Akrabb
  - Paket-Flexx
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: WA
  type: select
  disable-udp: false
  proxies:
  - MANUAL
  - AUTO
  - BYPASS
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: BYPASS
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '99'
script:
  code: |
    def main(ctx, metadata):
        directkeywordlist = ["whatsapp"]
        for directkeyword in directkeywordlist:
          if directkeyword in metadata["host"]:
            ctx.log('[Script] matched keyword %s use WA' % directkeyword)
            return "WA"
        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "443":
                ctx.log('[Script] matched QUIC traffic use UMUM')
                return "UMUM"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889, 9993]
        if port not in port_list:
            ctx.log('[Script] not common port use BYPASS')
            return "BYPASS"

        if metadata["dst_ip"] == "":
            return "DIRECT"

        code = ctx.geoip(metadata["dst_ip"])
        if code == "ID":
            ctx.log('[Script] Geoip ID')
            return "UMUM"

        ctx.log('[Script] UMUM')
        return "UMUM"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- GEOIP,ID,UMUM
- MATCH,UMUM
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
secret: '123456'
bind-address: "*"
